apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc1
  annotations:
    volume.beta.kubernetes.io/storage-class: "ibmc-file-bronze"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi


