apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web-app
    spec:
      restartPolicy: Always
      hostname: app
      containers:	     
      - name: web
        image: registry.au-syd.bluemix.net/takara/web:v1
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /var/www
          name: www-vol
      - name: app
        image: registry.au-syd.bluemix.net/takara/app:v1
        env:
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: root
        resources: {}
        volumeMounts:
        - mountPath: /var/www
          name: www-vol
      initContainers:
      - name: cp-contents
        image: maho/web_contents:blue
        command: ["cp",  "-r", ".", "/var/www"]
      volumeMounts:
        - mountPath: /var/www
          name: www-vol
      volumes:
      - name: www-vol
        emptyDir: {}

